apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-bpji
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-wcvt-tenant/rhtap-demo-app/hacbs-test-project-bpji@sha256:434a54ca82e8869c01743d0d432c95a979f23458ae2d8d5a7a5cfea63ba7fe57
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
